CREATE VIEW tickets.tickets_view AS Select 
	connection.formant_id, 
	connection.jira_id, 
	connection.expert_connect_id,
	formant.device_name,
	formant.vehicle_id  as formant_vehicle_id, 
	formant.device_id, 
	formant.message, 
	formant.severity, 
	formant.stream_name , 
	formant.stream_type, 
	formant.tags  as formant_tags, 
	formant.value, 
	formant.time  as formant_time, 
	formant.url  as formant_url, 
	formant.created_at as formant_created_at, 
	formant.updated_at as formant_updated_at, 
	formant.type, 
	formant.bundle as formant_bundle, 
	formant.vadc_diagnostics, 
	formant.active,
	expert_connect.vehicle_id  as expert_connect_vehicle_id, 
	expert_connect.title as expert_connect_title, 
	expert_connect.description as expert_connect_description, 
	expert_connect.product as expert_connect_product, 
	expert_connect.machine_hours as expert_connect_hours, 
	expert_connect.serial_number as expert_connect_serial_number, 
	expert_connect.misc as expert_connect_misc, 
	expert_connect.resolution as expert_connect_resolution, 
	expert_connect.advisor_id as expert_connect_advisor_id, 
	expert_connect.team_id  as expert_connect_team_id, 
	expert_connect.contact_id  as expert_connect_contact_id, 
	expert_connect.created_at  as expert_connect_created_at, 
	expert_connect.updated_at as expert_connect_updated_at, 
	expert_connect.bundle as expert_connect_bundle, 
	expert_connect.ec_id  as expert_connect_ec_id,
	ec_tags.name as expert_connect_tag_name,
	ec_advisors.first_name as expert_connect_advisor_first_name,
	ec_advisors.last_name as expert_connect_advisor_last_name,
	ec_advisors.phone as expert_connect_advisor_phone,
	ec_advisors.email as expert_connect_advisor_email,
	ec_contacts.first_name as expert_connect_contact_first_name,
	ec_contacts.last_name as expert_connect_contact_last_name,
	ec_contacts.phone as expert_connect_contact_phone,
	ec_contacts.email as expert_connect_contact_email,
	ec_teams.name as expert_connect_team_name,
	ec_teams.division as expert_connect_team_division,
	jira.jira_ticket, 
	jira.project  as jira_project, 
	jira.description as jira_description, 
	jira.summary  as jira_summary, 
	jira.category  as jira_category, 
	jira.requirement  as jira_requirement, 
	jira.bundle as jira_bundle, 
	jira.machine_type  as jira_machine_type, 
	jira.roadmap_item  as jira_roadmap_item, 
	jira.formant_link  as jira_formant_link, 
	jira.expert_connect_link  as jira_expert_connect_link, 
	jira.issue_type  as jira_issue_type, 
	jira.created_at  as jira_created_at, 
	jira.updated_at as jira_updated_at, 
	jira.priority as jira_priority, 
	jira.team_id as jira_team_id, 
	jira.bug_source as jira_bug_source
	
from tickets.connection as connection
inner join tickets.formant as formant ON formant.id = connection.formant_id
inner join tickets.expert_connect as expert_connect ON expert_connect.id = connection.expert_connect_id
inner join tickets.jira as jira ON jira.id = connection.jira_id
left outer join tickets.expert_connect_ticket_tags as ec_ticket_tags ON ec_ticket_tags.ticket_id = expert_connect.id
left outer join tags.expert_connect as ec_tags ON ec_tags.id = ec_ticket_tags.tag_id
left outer join personnel.expert_connect_advisors as ec_advisors ON ec_advisors.id = expert_connect.advisor_id
left outer join personnel.expert_connect_teams as ec_teams ON ec_teams.id = expert_connect.team_id
left outer join personnel.expert_connect_contacts as ec_contacts ON ec_contacts.id = expert_connect.contact_id