import { describe, it } from "mocha";
import { expect, assert } from "chai";
import { vaidateExpertConnectTicket } from "../validateExpertConnectTicket.js";

describe("vaidateExpertConnectTicket", () => {
  let data = {
    expertConnectTicket: {
      data: {
        tags: [],
      },
    },
  };

  before(() => {
    data.expertConnectTicket.data.tags.push({ name: "AutoGenerated" });
  });

  it("should be a valid expert connect ticket", () => {
    const isValid = vaidateExpertConnectTicket(data);

    expect(isValid).to.not.be.null;
    expect(isValid).to.not.be.null;
  });

  it("should be an invalid expert connect ticket", () => {
    data.expertConnectTicket.data.tags.length = 0;
    const isValid = vaidateExpertConnectTicket(data);

    expect(isValid).to.be.null;
  });
});
