import _ from "lodash";

export function vaidateExpertConnectTicket(data) {
  if (!data || data === null) return null;

  const clonedData = _.cloneDeep(data);
  const expertConnectTicket = clonedData.expertConnectTicket;

  try {
    if (
      !expertConnectTicket ||
      !expertConnectTicket.data ||
      !expertConnectTicket.data.tags ||
      !expertConnectTicket.data.tags.length ||
      !(
        expertConnectTicket.data.tags.find((tag) => tag.name === "Vision") ||
        expertConnectTicket.data.tags.find(
          (tag) => tag.name === "AutoGenerated"
        )
      )
    ) {
      throw new Error("Expert Connect ticket is not valid");
    } else {
      return clonedData;
    }
  } catch (e) {
    // console.log(e.message);
    // console.log(e.stack);

    return null;
  }
}
